config/routes.rb
Rails.application.routes.draw do
  root 'cars#index'
  get 'sign-up', to: 'registrations#new'
  post 'sign-up', to: 'registrations#create'
  get 'sign-out', to: 'authentication#destroy'
  get 'sign-in', to: 'authentication#new'
  post 'sign-in', to: 'authentication#create'
  resources :cars
end

app/models/car.rb
class Car < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    User.find_by(id: session[:user_id])
  end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Thank you for logging in!"
      redirect_to root_path
    else
      flash[:notice] = "something went horribly wrong!"
      render :new
    end
  end

  def destroy
    session.destroy
    redirect_to root_path
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only:[:show, :edit, :update]
  def index
    @cars = Car.all
  end

  def show
  end

  def new
    @car = Car.new
  end

  def create
    car = Car.new(car_params)
    if car.save
      flash[:notice] = "You succesfully created a new car"
      redirect_to car_path(car)
    else
      @car = car
      render :new
    end
  end

  def edit
  end

  def update
    if @car.update(car_params)
      flash[:notice] = "You successfully updated your car"
      redirect_to car_path(@car)
    else
      render :edit
    end
  end

  def destroy
    Car.find(params[:id]).destroy
    flash[:notice] = "Your car just blew up!"
    redirect_to cars_path
  end

  private

  def car_params
    params.require(:car).permit(:make, :model, :year)
  end

  def set_car
    @car = Car.find(params[:id])
  end
  
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:email, :password))
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Thank you for Signing up!"
      redirect_to root_path
    else
      render :new
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authentication/new.haml
= form_tag sign_in_path do
  = label_tag :email
  = email_field_tag :email
  = label_tag :password
  = password_field_tag :password
  = submit_tag "login"

app/views/cars/_form.haml
= form_for @car do |f|
  = f.label :make
  = f.text_field :make
  .div
    = f.label :model
    = f.text_field :model
  .div
    = f.label :year
    = f.date_field :year
  .div
    = f.submit
= link_to 'back', cars_path

app/views/cars/edit.haml
%h1 Edit Car
= render 'form'

app/views/cars/index.haml
List of Cars
- @cars.each do |car|
  %p= car.make
  %p= car.model
  %p= car.year
  = link_to 'edit', edit_car_path(car)
  = link_to 'delete', car_path(car), method: :delete
= link_to 'New Car', new_car_path

app/views/cars/new.haml
%h1 New Car!
= render 'form'

app/views/cars/show.haml
=@car.make
=@car.model
=@car.year
= link_to 'back', cars_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CarsAppWithAuth
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    -if flash[:notice]
      %p= flash[:notice]
    -if current_user
      = link_to 'Logout', sign_out_path
    -else
      = link_to 'Login', sign_in_path
      = link_to 'Sign Up', sign_up_path
    = yield